### ISSUE TITLE
Правки по дизайну от ревьюера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/Design#13]
В целом: использовать как можно больше компонентов и автолейаутов

- [x] Создать текстовое поле рядом с китом, где каждая из вас будет записывать изменения по компонентам, чтобы если что-то изменилось, то это изменилось везде и не потерялось. Формата: Саша, 10.10, изменила компонент такой-то
- [x] Подписать все компоненты в UI ките

Общее:

- [ ] Сделать UI - kit более подробным с компонентами
- [x] Во всех зеленых кнопках сделать белый текст
- [x] Сделать шрифты у заголовков меньше и серым цветом на всех экранах (которые самые большие типа "О нас", "Регистрация")
- [x] Весь текст на сайте тоже сделать серым
- [x] Увеличить межстрочное расстояние у текстов 
- [x] Увеличить размер текста внутри полей (например 20)
- [x] Сделать серую обводку полей везде (возможно в цвет заголовков)
- [x] Сделать заголовки к полям серым цветом везде (сейчас в регистрации серым, а в форме ОС черные)
- [x] Текст внутри полей светло - серым цветом, размера как и заголовки к полям (например 20)
- [ ] Сделать все модальные окна одинаковыми, закрепить их размер в Фигме (исправить модальное окно выхода из ЛК)

В новостях на главной:

- [x] Увеличить шрифт в кнопке "ко всем новостям", сделать её зеленой с белым шрифтом (как у кнопок ниже)
- [x] В хэштегах в новостях сделать белый цвет шрифта
- [x] Цвет заголовка в новостях не меняем тк карточка новости разворачивается при клике на картинку

В форме ОС сделать:

- [x]  * у поля для текста (все поля у формы являются обязательными)
- [x] сделать описание в форме, формата: если у вас остались вопросы, вы можете связаться с нами через форму обратной связи и мы обязательно ответим вам в течении 3 дней
- [x] Сделать цвет подсказки такого же цвета как и подсказки в соседних полях: имя, телефон, почта
- [x] Сделать шрифт подсказки как во всех полях 
- [x] Сделать одинаковое скругление полей формы
- [x] Подписать текстовое поле таким же заголовком как "Имя", например можно назвать "текст обращения"
- [x] Убрать модалку после отправки формы ОС и сделать всплывающую подсказку, которая исчезает через несколько секунд
- [x] Ширину кнопки у "связаться с нами" сделать такой же как у "стать волонтером/организатором"

В авторизации:

- [x] Сделать дополнительную кнопу "зарегистрироваться" Насть, у нас уже есть этот экран сделанный, просто подставить его
- [x] Сделать текст в зеленой кнопке белым цветом
- [x] Сделать ссылку "я вспомнил пароль" побольше шрифт
- [x] Сделать ссылку "забыл пароль" такого же размера как и "вспомнил пароль"
- [x] Сделать заголовки точно такие же как на главной (исправленный вариант) (возможно имеет смысл сделать заголовки элементом, чтобы они везде поменялись, если сейчас не так)
- [x] Увеличить лейблы в полях как и везде (тоже можно сразу элементом сделать)

В регистрации:

- [x] увеличить заголовки к полям "пароль" "повторить пароль" на 17 шрифт 
- [x] Сделать серую обводку полей
- [x] Увеличить шрифт в вариантах в выпадающих шрифтах:  в навыках и городе (сделать таким же как шрифт в поле)
- [x] Увеличить межсрочное растояние в выпадающем списке
- [x] Ссылку в модальном окне сделать черным цветом (или серым, если весь текст будет серым)
- [x] Сделать одинаковый свитчер у волонтера и организатора при регистрации 

В проектах:

- [x] Табы в проектах имеют другое скругление чем все остальные поля (сделать такое же скругление как везде)
- [x] Картинки на фоне карточки вставить 3 разных варианта (подложку), можно как раз вернуть листья и еще что-то 3
- [x] В карточке проекта кавычки у названия организации изменить на кавычки-елочки
- [x] текст в зеленых кнопках белым цветом

В ЛК:

- [x] Если размер превью карточек проектов в ЛК сделаем такие же как на странице проектов, то если там будет всего 2 столбца карточек, нормально будет смотреться ? (давайте рядом попробуем так сделать)
- [x] Исправить то что писал Дима в чате

**Comment by kseniia2673** [comment]
.

**Comment by artlightning** [comment]
В проектах:

- [x]  Табы в проектах имеют другое скругление чем все остальные поля (сделать такое же скругление как везде)
- [x]  Картинки на фоне карточки вставить 3 разных варианта (подложку), можно как раз вернуть листья и еще что-то 3
- [x]  В карточке проекта кавычки у названия организации изменить на кавычки-елочки
- [x]  текст в зеленых кнопках белым цветом

В ЛК:

- [x]  Если размер превью карточек проектов в ЛК сделаем такие же как на странице проектов, то если там будет всего 2 столбца карточек, нормально будет смотреться ? (давайте рядом попробуем так сделать и посмотреть ок ли так)
- [x]  Исправить то что писал Дима в чате

**Comment by artlightning** [comment]
- [x]  увеличить заголовки к полям "пароль" "повторить пароль" на 17 шрифт (вот тут если что на 20 тк теперь 20 везде)
- [x]  Сделать серую обводку полей
- [x]  Увеличить шрифт в вариантах в выпадающих шрифтах: в навыках и городе (сделать таким же как шрифт в поле)
- [x]  Увеличить межсрочное растояние в выпадающем списке
- [x]  Ссылку в модальном окне сделать черным цветом (или серым, если весь текст будет серым)
- [x]  Сделать одинаковый свитчер у волонтера и организатора при регистрации

**Comment by kseniia2673** [comment]
- [x] Разбить ФИО при регистрации на 3 поля (как было раньше)
